### ISSUE TITLE
Can't use system media controls app to control

### ISSUE THREAD

**Issue by gzyguo** [Windkracht8/WearMusicPlayer#1]
Headphone media next not working;
Media play pause button can't resume playback when play paused for a while.

**Comment by Windkracht8** [comment]
I'm working on an update that will publish more controls to media controllers, this should address this.

**Comment by Windkracht8** [comment]
Solved with https://github.com/Windkracht8/WearMusicPlayer/commit/32bbd951d4947b84bf88bdeedff3bcd1b9895f95
Update to Play Store is underway.
